# Configuration of local ci process for project
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    - id: check-byte-order-marker
    - id: detect-private-key


-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: "poetry run flake8"
        language: system
        types: [python]

    -   id: mypy
        name: mypy
        entry: "poetry run mypy"
        language: system
        types: [python]
