# Generated by Django 4.0.2 on 2022-02-17 11:32

from django.db import migrations, models



class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('short_info', models.CharField(
                    max_length=256,
                    unique=True,
                    verbose_name='краткое описание'
                )),
                ('description', models.TextField(verbose_name='Описание')),
                ('route', models.TextField(verbose_name='Маршрут до объекта')),
                ('return_route', models.TextField(verbose_name='Обратный маршрут')),
            ],
            options={
                'verbose_name': 'Достопримечательность',
                'verbose_name_plural': 'Достопримечательности',
                'db_table': 'attractions',
            },
        ),
    ]
