# Generated by Django 4.0.4 on 2022-05-27 20:47
# Edited for fixing style of code

import functools

from django.db import migrations, models
import django.db.models.deletion

import server.utilites



class Migration(migrations.Migration):
    initial = True
    dependencies = ()


    operations = (

        migrations.CreateModel(
            name='AboutUsPage',
            fields=(
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('content', models.TextField(
                    verbose_name='Текст'
                )),
            ),
            options={
                'verbose_name': 'О нас',
                'db_table': 'about_us_page',
            },
        ),

        migrations.CreateModel(
            name='Attraction',
            fields=(
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(
                    max_length=128,
                    unique=True,
                    verbose_name='Название'
                )),
                ('short_info', models.CharField(
                    max_length=256,
                    unique=True,
                    verbose_name='краткое описание'
                )),
                ('description', models.TextField(
                    verbose_name='Описание'
                )),
                ('audio_description', models.FileField(
                    blank=True,
                    null=True,
                    upload_to=functools.partial(server.utilites.build_upload_path, *(), **{
                        'base_path': 'audio'
                    }),
                    verbose_name='Аудио описание'
                )),
            ),
            options={
                'verbose_name': 'Достопримечательность',
                'verbose_name_plural': 'Достопримечательности',
                'db_table': 'attractions',
            },
        ),

        migrations.CreateModel(
            name='Route',
            fields=(
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('audio_description', models.FileField(
                    blank=True,
                    null=True,
                    upload_to=functools.partial(server.utilites.build_upload_path, *(), **{
                        'base_path': 'audio'
                    }),
                    verbose_name='Аудио описание маршрутов'
                )),
                ('attraction', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='routes',
                    to='main.attraction'
                )),
            ),
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'db_table': 'routes',
            },
        ),

        migrations.CreateModel(
            name='Photo',
            fields=(
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('caption', models.CharField(
                    max_length=128,
                    unique=True,
                    verbose_name='Подпись'
                )),
                ('image', models.ImageField(
                    upload_to=functools.partial(server.utilites.build_upload_path, *(), **{
                        'base_path': 'photo'
                    }),
                    verbose_name='Изображение'
                )),
                ('attraction', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='photos',
                    to='main.attraction'
                )),
            ),
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'db_table': 'photos',
            },
        ),

        migrations.CreateModel(
            name='MetroStation',
            fields=(
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('station_name', models.CharField(
                    max_length=80,
                    unique=True,
                    verbose_name='Название станции'
                )),
                ('station_type', models.CharField(
                    choices=[('m', 'станция метро'), ('mcc', 'станция МЦК')],
                    default='m',
                    max_length=3,
                    verbose_name='Тип станции'
                )),
                ('route_from_station', models.TextField(
                    verbose_name='Маршрут от станции до объекта'
                )),
                ('route_to_station', models.TextField(
                    verbose_name='Маршрут от объекта до станции'
                )),
                ('related_route', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='metro_stations',
                    to='main.route'
                )),
            ),
            options={
                'verbose_name': 'Станция метро',
                'verbose_name_plural': 'Станции метро',
                'db_table': 'metro_stations',
            },
        ),

    )
