# Generated by Django 4.0.2 on 2022-02-23 08:05

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):
    dependencies = [('main', '0001_initial'), ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='return_route',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='route',
        ),
        migrations.CreateModel(
            name='MetroStation',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('station_name', models.CharField(
                    max_length=80,
                    unique=True,
                    verbose_name='Название станции',
                )),
                ('route_from_station', models.TextField(
                    verbose_name='Маршрут от станции до объекта',
                )),
                ('route_to_station', models.TextField(
                    verbose_name='Маршрут от объекта до станции',
                )),
                ('attraction', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='nearest_metro_stations',
                    to='main.attraction',
                )),
            ],
            options={
                'verbose_name': 'Станция метро',
                'verbose_name_plural': 'Станции метро',
                'db_table': 'metro_stations',
            },
        ),
    ]
