# Generated by Django 4.1.1 on 2022-12-11 20:50

import functools

import django.core.validators
from django.db import migrations, models

from server.utilites import build_upload_path



class Migration(migrations.Migration):
    dependencies = (('main', '0002_route_address'),)

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('title', models.CharField(max_length=80, verbose_name='Название видео')),
                ('description', models.TextField(verbose_name='Описание видео')),
                ('video_file', models.FileField(
                    upload_to=functools.partial(build_upload_path, *(), **{'base_path': 'video'}),
                    validators=[
                        django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])
                    ],
                    verbose_name='Видео файл'
                )),
            ],
            options={
                'verbose_name': 'Видео',
                'db_table': 'videos',
            },
        ),
    ]
