# Generated by Django 4.0.2 on 2022-02-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('main', '0002_remove_attraction_return_route_and_more'), ]

    operations = [
        migrations.AddField(
            model_name='metrostation',
            name='station_type',
            field=models.CharField(
                choices=[('m', 'станция метро'), ('mcc', 'станция МЦК')],
                default='m',
                max_length=3,
                verbose_name='Тип станции'
            ),
        ),
    ]
