# Generated by Django 4.0.2 on 2022-04-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_metrostation_station_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='audio_description',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='audio',
                verbose_name='Аудио описание'
            ),
        ),
    ]
