# Generated by Django 4.0.2 on 2022-04-18 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_attraction_audio_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('caption', models.CharField(
                    max_length=128,
                    unique=True,
                    verbose_name='Подпись'
                )),
                ('image', models.ImageField(
                    upload_to='photo',
                    verbose_name='Изображение'
                )),
                ('attraction', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='photos',
                    to='main.attraction'
                )),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'db_table': 'photos',
            },
        ),
    ]
