# Generated by Django 4.0.4 on 2022-05-26 10:33

import functools

from django.db import migrations, models

import server.utilites


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_attraction_routes_audio'),
    ]


    operations = [

        migrations.AlterField(
            model_name='attraction',
            name='audio_description',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=functools.partial(server.utilites.build_upload_path, *(), **{
                    'base_path': 'audio'
                }),
                verbose_name='Аудио описание'
            ),
        ),

        migrations.AlterField(
            model_name='attraction',
            name='routes_audio',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=functools.partial(server.utilites.build_upload_path, *(), **{
                    'base_path': 'audio'
                }),
                verbose_name='Аудио описание маршрутов'
            ),
        ),

        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(
                upload_to=functools.partial(server.utilites.build_upload_path, *(), **{
                    'base_path': 'photo'
                }),
                verbose_name='Изображение'
            ),
        ),

    ]
