name: test
on: [push]


jobs:
  test-application:
    runs-on: [ubuntu-latest]
    steps:

      - name: Check out repository
        uses: actions/checkout@master


      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'


      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          installer-parallel: true


      - name: setup project
        run: make setup-development-env

      - name: run code quality checks
        run: make lint

      - name: run tests
        run: make test
